src/main/java/art/heredium/domain/membership/entity/Membership.java, src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepository.java, src/main/java/art/heredium/domain/membership/repository/MembershipRepository.java
https://jira.sotatek.com/browse/IH-20
=> IH-20 Create membership entities

src/main/java/art/heredium/controller/user/UserMembershipController.java, src/main/java/art/heredium/core/config/error/entity/ErrorCode.java, src/main/java/art/heredium/core/util/AuthUtil.java, src/main/java/art/heredium/domain/membership/entity/Membership.java, src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/domain/membership/model/dto/response/MembershipRegistrationResponse.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepository.java, src/main/java/art/heredium/service/MembershipRegistrationService.java
https://jira.sotatek.com/browse/IH-27
=> IH-27 Add getMembershipInfo API

src/main/resources/application-local.properties, src/main/resources/application-prod.properties, src/main/resources/application-stage.properties
Add env config for NICE Payment Gateway
=> IH-22 Implement NICE Payment env config

src/main/java/art/heredium/payment/nicepayments/dto/request/NicePaymentsPayRequest.java, src/main/java/art/heredium/payment/nicepayments/dto/response/NicePaymentsPayResponse.java, src/main/java/art/heredium/payment/nicepayments/feign/client/NicePaymentsClient.java, src/main/java/art/heredium/payment/nicepayments/feign/config/NicePaymentsFeignConfig.java, src/main/java/art/heredium/payment/nicepayments/feign/interceptor/NicePaymentsFeignRequestInterceptor.java
Implement NICE Payment approval payment API client
=> IH-23 Implement NICE Payment approval payment API client

src/main/java/art/heredium/controller/user/UserMembershipController.java, src/main/java/art/heredium/controller/user/UserPostController.java, src/main/java/art/heredium/core/config/error/entity/ErrorCode.java, src/main/java/art/heredium/domain/coupon/entity/Coupon.java, src/main/java/art/heredium/domain/coupon/entity/CouponUsage.java, src/main/java/art/heredium/domain/coupon/model/dto/response/CouponResponse.java, src/main/java/art/heredium/domain/membership/entity/Membership.java, src/main/java/art/heredium/domain/membership/model/dto/response/MembershipRegistrationResponse.java, src/main/java/art/heredium/domain/membership/model/dto/response/MembershipResponse.java, src/main/java/art/heredium/domain/membership/repository/MembershipRepository.java, src/main/java/art/heredium/domain/post/repository/PostRepository.java, src/main/java/art/heredium/service/MembershipService.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-32
=> IH-32 Add get memberships by post ID API

src/main/java/art/heredium/controller/admin/AdminPostController.java, src/main/java/art/heredium/domain/post/entity/Post.java, src/main/java/art/heredium/domain/post/model/dto/request/PostUpdateRequest.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-40
=> IH-40 Add Admin updateIsEnabled API for post

src/main/java/art/heredium/domain/ticket/model/dto/request/PostTicketHanaBankRequest.java, src/main/java/art/heredium/domain/ticket/model/dto/request/PostTicketNonUserRequest.java, src/main/java/art/heredium/domain/ticket/model/dto/request/PostTicketUserRequest.java, src/main/java/art/heredium/payment/dto/PaymentsPayRequest.java, src/main/java/art/heredium/payment/inf/PaymentRequest.java, src/main/java/art/heredium/payment/inicis/Inicis.java, src/main/java/art/heredium/payment/inicis/dto/request/InicisPaymentRequest.java, src/main/java/art/heredium/payment/nicepayments/NicePayments.java, src/main/java/art/heredium/payment/nicepayments/dto/request/NicePaymentsPayRequest.java, src/main/java/art/heredium/payment/tosspayments/TossPayments.java, src/main/java/art/heredium/payment/tosspayments/dto/request/TossPaymentsPayRequest.java, src/main/java/art/heredium/payment/type/PaymentType.java, src/main/java/art/heredium/service/TicketPayService.java
https://jira.sotatek.com/browse/IH-51
=> IH-51 Remove Ticket in payment models

src/main/java/art/heredium/controller/admin/AdminPostController.java, src/main/java/art/heredium/domain/coupon/model/dto/response/CouponResponseDto.java, src/main/java/art/heredium/service/CouponUsageService.java, src/main/java/art/heredium/service/PostService.java
=> Fix JDK compatible

src/main/java/art/heredium/domain/post/entity/Post.java, src/main/java/art/heredium/domain/post/model/dto/request/PostCreateRequest.java, src/main/java/art/heredium/service/PostService.java
Add thumnail fields for post
https://jira.sotatek.com/browse/IH-54
=> IH- 54 Add thumnail fields for post

src/main/java/art/heredium/controller/admin/AdminPostController.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-64
=> IH-64 Add api admin getPostDetail

src/main/java/art/heredium/controller/user/UserCouponController.java, src/main/java/art/heredium/domain/coupon/model/dto/response/CouponUsageResponse.java, src/main/java/art/heredium/service/CouponUsageService.java
https://jira.sotatek.com/browse/IH-73
=> IH-73 Add API getCouponByUuid

src/main/java/art/heredium/domain/post/entity/Post.java, src/main/java/art/heredium/domain/post/model/dto/request/PostCreateRequest.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-96
=> IH-96 Update API create post

src/main/java/art/heredium/controller/admin/AdminPostController.java, src/main/java/art/heredium/controller/user/UserPostController.java, src/main/java/art/heredium/domain/exhibition/repository/ExhibitionRepository.java, src/main/java/art/heredium/domain/post/entity/Post.java, src/main/java/art/heredium/domain/post/model/dto/request/PostCreateRequest.java, src/main/java/art/heredium/domain/post/model/dto/response/PostDetailsResponse.java, src/main/java/art/heredium/domain/post/repository/PostRepository.java, src/main/java/art/heredium/domain/program/repository/ProgramRepository.java, src/main/java/art/heredium/service/ExhibitionService.java, src/main/java/art/heredium/service/PostService.java, src/main/java/art/heredium/service/ProgramService.java
https://jira.sotatek.com/browse/IH-97
=> IH-97 Update API get post detail

src/main/java/art/heredium/controller/admin/AdminCouponController.java, src/main/java/art/heredium/core/util/Constants.java, src/main/java/art/heredium/core/util/ValidationUtil.java, src/main/java/art/heredium/domain/coupon/entity/Coupon.java, src/main/java/art/heredium/domain/coupon/model/dto/request/CouponCreateRequest.java, src/main/java/art/heredium/domain/coupon/validation/CouponValidationUtil.java, src/main/java/art/heredium/domain/membership/model/dto/request/MembershipCreateRequest.java, src/main/java/art/heredium/service/CouponService.java, src/main/java/art/heredium/service/MembershipService.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-105
=> IH-105 Create API add non-membership coupon

src/main/java/art/heredium/controller/admin/AdminCouponController.java, src/main/java/art/heredium/domain/coupon/entity/Coupon.java, src/main/java/art/heredium/domain/coupon/model/dto/request/CouponCreateRequest.java, src/main/java/art/heredium/domain/coupon/model/dto/request/MembershipCouponCreateRequest.java, src/main/java/art/heredium/domain/coupon/model/dto/request/NonMembershipCouponCreateRequest.java, src/main/java/art/heredium/domain/membership/model/dto/request/MembershipCreateRequest.java, src/main/java/art/heredium/service/CouponService.java, src/main/java/art/heredium/service/PostService.java
https://jira.sotatek.com/browse/IH-111
=> IH-111 Update api create non membership coupons

src/main/java/art/heredium/controller/admin/AdminPostController.java, src/main/java/art/heredium/controller/user/UserPostController.java, src/main/java/art/heredium/domain/post/model/dto/response/AdminPostDetailsResponse.java
https://jira.sotatek.com/browse/IH-109
=> IH-109 Refactor get post details api

src/main/java/art/heredium/payment/nicepayments/NicePayments.java, src/main/java/art/heredium/payment/nicepayments/dto/response/NicePaymentsBaseResponse.java
https://jira.sotatek.com/browse/IH-120
=> Ih-120 Skip payment process temporary for testing

src/main/java/art/heredium/domain/account/model/dto/request/GetAccountWithMembershipInfoRequest.java, src/main/java/art/heredium/domain/account/model/dto/response/AccountWithMembershipInfoResponse.java, src/main/java/art/heredium/domain/account/repository/AccountRepositoryImpl.java
- Update api get account list page 23
- https://jira.sotatek.com/browse/IH-121
=> IH-121 Update api get account list page 23

src/main/java/art/heredium/controller/admin/AdminCompanyController.java, src/main/java/art/heredium/core/config/error/entity/ErrorCode.java, src/main/java/art/heredium/domain/company/entity/Company.java, src/main/java/art/heredium/domain/company/model/dto/request/CompanyCreateRequest.java, src/main/java/art/heredium/domain/company/repository/CompanyRepository.java, src/main/java/art/heredium/domain/coupon/entity/Coupon.java, src/main/java/art/heredium/domain/coupon/entity/CouponSource.java, src/main/java/art/heredium/domain/coupon/entity/CouponUsage.java, src/main/java/art/heredium/domain/coupon/model/dto/request/CompanyCouponCreateRequest.java, src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/domain/membership/entity/RegistrationType.java, src/main/java/art/heredium/service/CompanyService.java, src/main/java/art/heredium/service/CouponService.java, src/main/java/art/heredium/service/CouponUsageService.java, src/main/java/art/heredium/service/MembershipRegistrationService.java
https://jira.sotatek.com/browse/IH-114
=> IH-114 Create API add company

src/main/java/art/heredium/controller/admin/AdminAccountController.java, src/main/java/art/heredium/domain/account/model/dto/request/GetAccountWithMembershipInfoIncludingTitleRequest.java, src/main/java/art/heredium/domain/account/model/dto/response/AccountWithMembershipInfoIncludingTitleResponse.java, src/main/java/art/heredium/domain/account/repository/AccountRepositoryImpl.java, src/main/java/art/heredium/domain/account/repository/AccountRepositoryQueryDsl.java, src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/domain/membership/entity/PaymentStatus.java, src/main/java/art/heredium/service/AccountService.java
https://jira.sotatek.com/browse/IH-116
=> IH-116 Create API search accounts with membership info

src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/service/MembershipRegistrationService.java
- https://jira.sotatek.com/browse/IH-122
=> IH-122 Update payment status and registation type

src/main/java/art/heredium/controller/admin/AdminMembershipController.java, src/main/java/art/heredium/domain/account/repository/AccountRepositoryImpl.java, src/main/java/art/heredium/domain/membership/model/dto/request/GetAllActiveMembershipsRequest.java, src/main/java/art/heredium/domain/membership/model/dto/response/ActiveMembershipRegistrationsResponse.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepository.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepositoryImpl.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepositoryQueryDsl.java, src/main/java/art/heredium/service/MembershipService.java
https://jira.sotatek.com/browse/IH-128
=> IH-128 Create API search all active memberships with filter condition

src/main/java/art/heredium/controller/user/UserMembershipController.java, src/main/java/art/heredium/core/config/error/entity/ErrorCode.java, src/main/java/art/heredium/domain/membership/entity/MembershipRegistration.java, src/main/java/art/heredium/domain/membership/model/dto/request/MembershipConfirmPaymentRequest.java, src/main/java/art/heredium/domain/membership/model/dto/response/MembershipConfirmPaymentResponse.java, src/main/java/art/heredium/domain/membership/repository/MembershipRegistrationRepository.java, src/main/java/art/heredium/service/MembershipPaymentService.java, src/main/java/art/heredium/service/MembershipRegistrationService.java
- Create api confirm payment for register membership
- https://jira.sotatek.com/browse/IH-137
=> IH-137 Create api confirm payment for register membership

src/main/java/art/heredium/payment/nicepayments/NicePayments.java
IH-155 Skip payment confirmation on the BE side
=> IH-155 Skip payment confirmation on the BE side

src/main/java/art/heredium/payment/tosspayments/TossPayments.java
=> IH-172 Add TossPayment retry

src/main/java/art/heredium/payment/tosspayments/TossPayments.java
Refactor payment type priority
=> IH-172 Refactor payment type priority

src/main/java/art/heredium/domain/account/model/dto/response/CouponIssuanceUploadResponse.java, src/main/java/art/heredium/domain/account/repository/AccountRepositoryImpl.java
IH-181 Add email to coupon issuance response
=> IH-181 Add email to coupon issuance response

src/main/java/art/heredium/controller/admin/AdminCouponController.java, src/main/java/art/heredium/service/CouponService.java
-  Create api get coupon detail
=> IH-190 Create api get coupon detail

src/main/java/art/heredium/domain/post/entity/Post.java, src/main/java/art/heredium/domain/post/model/dto/request/PostCreateRequest.java, src/main/java/art/heredium/domain/post/model/dto/request/PostUpdateRequest.java, src/main/java/art/heredium/domain/post/model/dto/response/AdminPostDetailsResponse.java, src/main/java/art/heredium/domain/post/model/dto/response/PostDetailsResponse.java, src/main/java/art/heredium/service/PostService.java
Apply subTitle and openDate for post
=> IH-195 Apply subTitle and openDate for post

src/main/java/art/heredium/domain/account/repository/AccountRepositoryImpl.java
This reverts commit 0b5ba3943ca8f9dd972969462c2faf4cde0b7ea9.
=> Revert IH-239 Fix error with total amount in admin dashboard

src/main/java/art/heredium/domain/company/entity/Company.java, src/main/java/art/heredium/domain/company/model/dto/request/CompanyUpdateRequest.java, src/main/java/art/heredium/domain/company/repository/CompanyRepository.java, src/main/java/art/heredium/service/CompanyService.java, src/main/resources/sql/20250228/remove_is_deleted_in_company_table.sql
Delete company permanently
Ref: https://chat.google.com/room/AAAAdLfOtqg/Z9t3Ovp-pGI/KZct7lYou_o?cls=10
=> IH-249 Delete company permanently
